//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormForFruityBomb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormForFruityBomb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonardo_Phoenix_A_stylized_vibrant_cherry_symbol_isolated_on_1_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Leonardo_Phoenix_A_stylized_vibrant_cherry_symbol_isolated_on_1-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonardo_Phoenix_Create_a_stylized_Bell_symbol_for_a_casino_ga_3_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Leonardo_Phoenix_Create_a_stylized_Bell_symbol_for_a_casino_ga_3-removebg-preview" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonardo_Phoenix_Create_a_vibrant_cinematic_background_design_2 {
            get {
                object obj = ResourceManager.GetObject("Leonardo_Phoenix_Create_a_vibrant_cinematic_background_design_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonardo_Phoenix_create_a_vibrant_stylized_eggplant_symbol_on_3_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Leonardo_Phoenix_create_a_vibrant_stylized_eggplant_symbol_on_3-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonardo_Phoenix_Design_a_vibrant_and_eyecatching_logo_for_Fru_0_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Leonardo_Phoenix_Design_a_vibrant_and_eyecatching_logo_for_Fru_0-removebg-preview" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonardo_Phoenix_design_a_vibrant_and_stylized_watermelon_slic_0_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Leonardo_Phoenix_design_a_vibrant_and_stylized_watermelon_slic_0-removebg-preview" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
